name = "Interview Prep"
license = "MIT"
licenselink = "https://github.com/kubesimplify/interview-prep/blob/main/LICENSE"
description = "Interview Prep is a collection of interview questions and answers for Cloud Native Space."

homepage = "https://github.com/kubesimplify/interview-prep"
demosite = "https://interview-prep.vercel.app"

tags = ["cloud native", "interview prep", "interview questions", "interview answers", "interview preparation", "interview practice", "interview preparation", "interview practice", "interview preparation", "interview practice"]
features = ["cloud native", "interview prep", "interview questions", "interview answers", "interview preparation", "interview practice", "interview preparation", "interview practice", "interview preparation", "interview practice"]

[author]
  name = "KubeSimplify"
  homepage = "https://kubesimplify.com"
